#!/bin/python3

import math
import os
import random
import re
import sys

def countApplesAndOranges(s, t, a, b, apples, oranges):
    # Write your code here
    apple_landing = [a + ele for ele in apples]
    orange_landing = [b + ele for ele in oranges]
    apple_in_house, orange_in_house = 0, 0
    for apple in apple_landing:
        if apple in range(s, t+1):
            apple_in_house += 1
    for orange in orange_landing:
        if orange in range(s, t+1):
            orange_in_house += 1
    print(apple_in_house)
    print(orange_in_house)

if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()

    s = int(first_multiple_input[0])

    t = int(first_multiple_input[1])

    second_multiple_input = input().rstrip().split()

    a = int(second_multiple_input[0])

    b = int(second_multiple_input[1])

    third_multiple_input = input().rstrip().split()

    m = int(third_multiple_input[0])

    n = int(third_multiple_input[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)
