#!/bin/python3

import math
import os
import random
import re
import sys


def climbingLeaderboard(ranked, player):
    # Write your code here
    unique_rank = sorted(list(set(ranked)), reverse=True)
    current_player_rank = []
    for playing_score in player:
        while unique_rank and playing_score >= unique_rank[-1]:
            unique_rank.pop()
        current_player_rank.append(len(unique_rank) + 1)
    
    return current_player_rank

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ranked_count = int(input().strip())

    ranked = list(map(int, input().rstrip().split()))

    player_count = int(input().strip())

    player = list(map(int, input().rstrip().split()))

    result = climbingLeaderboard(ranked, player)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
