#!/bin/python3

import math
import os
import random
import re
import sys

def countingValleys(steps, path):
    # Write your code here
    hike_level = 0
    valley_count = 0
    for path_step in path:
        if path_step == 'U':
            hike_level += 1
            if hike_level == 0:
                valley_count += 1
        else:
            hike_level -= 1
    
    return valley_count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    steps = int(input().strip())

    path = input()

    result = countingValleys(steps, path)

    fptr.write(str(result) + '\n')

    fptr.close()
