#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter

def migratoryBirds(arr):
    # Write your code here
    bird_counts = Counter(arr)
    return(max(bird_counts.keys(),key=lambda x:(bird_counts[x],-x)))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr_count = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = migratoryBirds(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
