#!/bin/python3

import math
import os
import random
import re
import sys

def miniMaxSum(arr):
    # Write your code here
    min_num, max_num, sum_val = arr[0], arr[0], arr[0]
    for i in range(1, len(arr)):
        sum_val += arr[i]
        if arr[i] < min_num:
            min_num = arr[i]
        elif arr[i] > max_num:
            max_num = arr[i]
    print((sum_val - max_num), (sum_val - min_num))

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
