#!/bin/python3

import math
import os
import random
import re
import sys

def sockMerchant(n, ar):
    # Write your code here
    unique_socks_color = set(ar)
    total_possible_pairs = 0
    for colour in unique_socks_color:
        possible_pair = ar.count(colour) // 2
        total_possible_pairs += possible_pair
    
    return total_possible_pairs

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
