#!/bin/python3

import math
import os
import random
import re
import sys
from datetime import datetime
from datetime import timedelta

# Complete the time_delta function below.
def time_delta(t1, t2):
    
    Format = '%a %d %b %Y %H:%M:%S %z'
    tdelta = datetime.strptime(t1, Format) - datetime.strptime(t2, Format)
    return str(int(abs(timedelta.total_seconds(tdelta))))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        t1 = input()

        t2 = input()

        delta = time_delta(t1, t2)

        fptr.write(delta + '\n')

    fptr.close()
